services:
  app:
    build: .
    container_name: typexhub
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./database:/var/www/html/database
      - ./.env:/var/www/html/.env
    networks:
      - app-network
    environment:
      DB_HOST: db                    # ✅ Use o nome do serviço diretamente
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}

  db:
    image: mysql:latest
    container_name: typexhub-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # ❌ Removido MYSQL_HOST (não é variável válida do MySQL)
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}         # ✅ Certifique-se que DB_USER ≠ "root"
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db                   # ✅ Correto
      PMA_PORT: 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local