# docker-compose.yml
services:
  app:
    build: .
    container_name: typexhub
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:latest
    container_name: typexhub-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'typexutfpr'
      MYSQL_DATABASE: 'typexhub'
      MYSQL_USER: 'typexadmin'
      MYSQL_PASSWORD: 'typexadmin'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Serviço do phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: meu_app_pma
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local